FROM node:18-alpine

WORKDIR /app

# Copy package files
COPY package.json ./
COPY yarn.lock ./
RUN yarn

# Copy the rest of the code
COPY . .

# Build environment variables will be set from docker-compose
ENV API_URL=http://backend:8000

EXPOSE 3000
CMD ["npm", "run", "dev"]