services:
  # Application service
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./data:/data
    depends_on:
      - mongodb
    env_file: .env
    restart: always
    networks:
      - app-network

  # MongoDB Database
  mongodb:
    image: mongo:latest
    env_file: .env
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_data:/data/db
      - ./db_confs/mongod.conf:/etc/mongo/mongod.conf
    command: ["mongod", "--config", "/etc/mongo/mongod.conf"]
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo_data:
